version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=canacintra
      - POSTGRES_USER=canacintra_admin
      - POSTGRES_PASSWORD=12345678
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@canacintra.com
      - PGADMIN_DEFAULT_PASSWORD=12345678
    ports:
      - 5050:80